### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by mrjjwright** [adamhaile/S#19]
Hi, absolutely love the speed, robustness, and elegance of S.js.

I am building something with S.js that requires me to keep a large data structure that looks something like a `Map<string, DataSignal<any>>`.   I would like the insertions and deletions to the Map to be reactive because some of the computations in the map rebuild their computed values based on other values in the map being available or not available .  

I don't need Mobx in this application, or else I would use it's reactive Map, because it's a very low level app, where the performance of S.js is desired.   Any idea for a simple way to achieve observing some kind of keyed data structure with S.js?   It doesn't have to a true ES6 Map, just some way to achieve the desired effect.

**Comment by ryansolid** [comment]
I don't think there is an existing library for Maps. But perhaps @adamhaile would know.

But to create this yourself, each value is already a data signal, you only need one additional signal to represent the whole Map.  One that gets set whenever you need to indicate the Map is dirty (needs it's dependencies to recalculate) and is accessed whenever the Map is read.

Generally if you want this obscured you are going to have to wrap the data structure in some way so that you can intercept at minimum the get and set methods. There are so many different approaches to this from Getter/Setters to Proxies but the simplest might just be to wrap the Map with your own Class that wraps the native methods. Look at [S-Array](https://github.com/adamhaile/S-array) for an example of how this is achieved for Arrays.  

```js
class SMap {
    constructor() {
        this.map = new Map();
        this.dirty = S.data(false);
    }

    get(key) {
        // track dependency
        this.dirty();
        return this.map.get(key);
    }

    set(key, value) {
        this.map.set(key, value);
        // trigger dependencies
        this.dirty(true);
    }
}
```
However, it's a matter of how far you want to take this. Solving these nested structures is one of a few reasons libraries like MobX has been moving to using Proxies.

**Comment by mrjjwright** [comment]
That’s helpful, thanks!  Adding one additional signal per entry so that its addition or deletion can be observed makes obvious sense for my use case now that I think about it this way.    Not sure how to judge the performance of this approach vs mobx maps without testing, but I suspect it will still be faster.

**Comment by mrjjwright** [comment]
Something like this is what I was thinking but perhaps this is completely wrong.

```javascript
import S, { DataSignal } from "s-js"

export function ObservableMap<T>(values?: { [id: string]: T }) {
  const keySignals: { [key: string]: DataSignal<string | null> } = {}
  const valueSignals: { [key: string]: DataSignal<T | null> } = {}

  if (values) {
    Object.keys(values).forEach(key => {
      const value = values[key]
      valueSignals[key] = S.data(value)
      keySignals[key] = S.data(key)
    })
  }

  function set(key: string, value: T) {
    let keySignal = keySignals[key]
    if (!keySignal) {
      keySignal = S.data(key)
    }
    let valueSignal = valueSignals[key]
    if (!valueSignal) {
      valueSignal = S.data(value)
      valueSignals[key] = valueSignal
    } else valueSignal(value)
  }

  function get(key: string): T | null {
    const valueSignal = valueSignals[key]
    return valueSignal ? valueSignal() : null
  }

  function remove(key: string) {
    const keySignal = keySignals[key]
    if (keySignal) keySignal(null)
    const valueSignal = valueSignals[key]
    if (valueSignal) valueSignal(null)
    else throw new Error(`Cannot find key ${key}`)
  }

  return {
    get,
    set,
    remove
  }
}

```

**Comment by adamhaile** [comment]
I've come to prefer a pretty minimalist approach for maps:

```typescript
function SMap<T, U>() {
    const map = new Map<T, DataSignal<U | null>>(); // I use null for unset, could be undefined
    return function SMap(key : T) { // function stmt gives friendly name in stack traces
        if (!map.has(key)) map.set(key, S.data(null));
        return map.get(key)
    };
}
```

Really all that does is make sure that readers and writers are working on the same data signal for the same key, no matter which runs first.

A couple subtleties around synchronicity and reactivity.  (Just for background, "synchronous" here is not the same meaning as when we talk about asynchronous code like promises, etc.  Synchronous in this usage comes from Synchronous Reactive Programming and means that all computations affected by a data change run in the same "logical instant".  This means there are no observable data changes during execution of the round.  If there were, then there would be a "before" and "after" that change, meaning two instants):

- Ryan, you may have realized this, but your first version isn't synchronous, in that sets take effect immediately, rather than with the next tick. 
- The second version has a subtle race condition: if a setter gets to a key before a reader, then the reader gets the just-set value in the first tick the key exists, but if the reader gets there first, it gets `null` in the first tick then the updated value in the following tick.  So you end up with an implicit dependency on the execution order of the reader and setter.
- John, your version's `.exists(key)` isn't reactive -- if a computation reads it and gets `false`, then the key is later created, it won't update.  Also, it assumes that if a key is `.remove()`'d, then computations that had read that key should not update if the same key is later re-set.  In my minimalist version, these methods become just `map(key)() !== null` for `exists()` and `map(key)(null)` for `remove()`.

All that said, in most of my S apps, the data structure I've found myself reaching for isn't a map but an index, i.e. it takes an array signal and a key function and 'indexes' the items in the array by the key function.  I can post up code if you're interested.
-- Adam

**Comment by mrjjwright** [comment]
Please share code for the array indexing of keys approach.  Thank you so much!!  Still processing.

**Comment by ryansolid** [comment]
Thanks for pointing that out Adam. It's not something that I have particularly thought about much. To this point I've been using S much the way I've always used similar looking libraries. I am usually much more concerned with trackable state that I'm not thinking about non-tracked (ie not in signal changes), but as you point out in the second scenario it can cause an unnecessary recalculation before settling in the right place.  I suppose it's time I freshen up on SRP.

I will say the one thing that led me to the dirty signal approach was the comment in the original post that said: 

> I would like the insertions and deletions to the Map to be reactive because some of the computations in the map rebuild their computed values based on other values in the map being available or not available

I've sort of done a similar approach to the 2nd version in Solid proxies where I don't use Maps but keyed objects. Like the data output from Normalizr with say GraphQL where I'm using Base64 ids made from concatting Model Name and Database Ids. If I iterate over that list say for a view the dependencies for keys not yet there aren't being made explicitly so I need a way to tell that computation to retrigger. But if iteration isn't a concern I do see that any explicit key access would always create the right dependencies here since you are creating them on get (including the get that fails to find). Which makes this much much simpler.

So in any case I'm interested in any alternative approaches, since while maybe not directly applicable can serve as inspiration on further optimizations, or better correctness when handling these sort of scenarios.

**Comment by ryansolid** [comment]
In regards to the dirty tracking you could do it that way. For arrays we are pretty used to using rest operators, concating, or other immutable methods to clone the array and set the Signals so it's why I feel less awkward setting it. If I were to make a pure Map option I'd expect this handled for me, But I think this is probably more inspired from the desire of encapsulating existing data structure uses than what makes the most sense to how to pattern code with Signals.

**Comment by mrjjwright** [comment]
Wow, this is so helpful, thank you ever so much!

**Comment by mrjjwright** [comment]
This is pretty bad ass. 🚀

**Comment by mrjjwright** [comment]
I made a 2 line change to add a `rootIndex` optional param, which adds the ability for a UniqueIndex to have a parent/root index so that if you want to keep a sub index that sources it's values from a root index, e.g. in an app where that root data must be kept in a single place, you can.  Not sure if I did it right but it's working well for me:

```typescript
import S, { DataSignal } from "s-js"
import { map } from "s-array"

type id = string | number

export type UniqueIndex<T> = (id: id | (() => id)) => DataSignal<T | null>

const UNSET = {}

export default function uniqueIndex<T>(
  array: () => T[],
  keyFn: (v: T) => id,
  rootIndex?: UniqueIndex<T>
): UniqueIndex<T> {
  const index = {} as { [id: string]: DataSignal<T | null> },
    // how many items have this key.  must be 0 or 1 at end of update
    slotCounts = {} as { [id: string]: number },
    // change data: which keys, items and how many are changing
    changeKeys = [] as id[],
    changeItems = [] as T[], // parallel to changeKeys
    slot = (id: id): DataSignal<T | null> => {
      return id in index
        ? index[id]
        : (index[id] = rootIndex ? rootIndex(id) : S.data(null))
    }

  let changeCount = 0

  const incKey = (item: T, key: id) => {
      if (key in slotCounts) slotCounts[key]++
      else slotCounts[key] = 1
      changeKeys[changeCount] = key
      changeItems[changeCount] = item
      changeCount++
    },
    decKey = (item: T, key: id) => {
      slotCounts[key]--
      changeKeys[changeCount] = key
      changeItems[changeCount] = UNSET as T
      changeCount++
    },
    changeBuilder = map(
      array,
      (item, oldkey) => {
        const key = keyFn(item)
        if (key !== oldkey) {
          if (oldkey !== undefined) decKey(item, oldkey)
          incKey(item, key)
        }
        return key
      },
      decKey
    ),
    updater = S.on(changeBuilder, () => {
      let errors = ""

      while (changeCount) {
        changeCount--
        const key = changeKeys[changeCount],
          item = changeItems[changeCount],
          slotCount = slotCounts[key],
          _slot = slot(key)

        changeItems[changeCount] = UNSET as T // memory safe: remove ref to item

        if (slotCount === 0) {
          _slot(null)
        } else if (slotCount === 1) {
          if (item !== UNSET) _slot(item)
        } else {
          if (item !== UNSET) errors += "key: " + key + ", item: " + item + ". "
          slotCounts[key] = 1 // restore sane state
        }
      }

      if (errors) throw new Error("UniqueIndex collision(s): " + errors)
    })

  return (id: id | (() => id)): (() => T | null) =>
    typeof id === "function" ? () => slot(id())() : slot(id)
}

**Comment by mrjjwright** [comment]
@adamhaile  Is it ok to share 2 different unique indexes over the same SArray?
