### ISSUE TITLE
Make methods treeshake-able

### ISSUE THREAD

**Issue by luwes** [adamhaile/S#22]
I noticed all static methods are put on the S function. 

I think it would pretty easy to make these separate exports instead and your consumers would get the benefit of being able to tree-shake some of the lesser used functions.

**Comment by adamhaile** [comment]
Yeah, exactly, this is a side-effect of making the main `S` export a function and attaching others to it, rather than `S` being a module.  I've gone both ways on whether that was originally a good idea or not.   The main issue that has kept things the way they are is that fixing it would be a breaking change for all S code.  All usages of `S(() => ...)` would have to switch to something like `S.comp(() => ...)`.  So far, it hasn't felt like the small size savings are worth breaking everybody's code.

**Comment by luwes** [comment]
Ah yes, makes sense. Might indeed not be worth it then.

**Comment by marvinhagemeister** [comment]
What if we export `S` as the `defsult` export and make all others as a named one. I can make a PR if needed.
