### ISSUE TITLE
Can this nested computation behavior be explained?

### ISSUE THREAD

**Issue by Qix-** [adamhaile/S#27]
Hey Adam.

```javascript
const S = require('s-js');

const i = S.data(0);
const j = S.data(0);
const k = S.data(0);
const l = S.data(0);

function show() {
	console.error({i:i(), j:j(), k:k(), l:l()});
}

console.log('-- INIT --');
S.root(() => {
	S(() => {
		console.error('start i->j');
		j(i());
		console.error({i:S.sample(i), j:S.sample(j)});

		S(() => {
			console.error('start j->k');
			k(j());
			console.error({j:S.sample(j), k:S.sample(k)});

			S(() => {
				console.error('start k->l');
				l(k());
				console.error({k:S.sample(k), l:S.sample(l)});
				console.error('end k->l');
			});

			console.error('end j->k');
		});

		console.error('end i->j');
	});
});

console.log('-- i=10 --');
i(10);
show();
console.log('-- i=30 --');
i(30);
show();
```

Apologies for all of the debug output.

The above computations are just `j = i`, `k = j`, `l = k`, but nested within one another. I log when the function is entered and when it completes, and show the samples of each of the associated variables at each step.

However, the output really surprised me.

```
-- INIT --
start i->j
{ i: 0, j: 0 }
start j->k
{ j: 0, k: 0 }
start k->l
{ k: 0, l: 0 }
end k->l
end j->k
end i->j
start j->k
{ j: 0, k: 0 }
start k->l
{ k: 0, l: 0 }
end k->l
end j->k
start k->l
{ k: 0, l: 0 }
end k->l
-- i=10 --
start i->j
{ i: 10, j: 0 }
start j->k
{ j: 0, k: 0 }
start k->l
{ k: 0, l: 0 }
end k->l
end j->k
end i->j
start j->k
{ j: 10, k: 0 }
start k->l
{ k: 0, l: 0 }
end k->l
end j->k
start k->l
{ k: 10, l: 0 }
end k->l
{ i: 10, j: 10, k: 10, l: 10 }
-- i=30 --
start i->j
{ i: 30, j: 10 }
start j->k
{ j: 10, k: 10 }
start k->l
{ k: 10, l: 10 }
end k->l
end j->k
end i->j
start j->k
{ j: 30, k: 10 }
start k->l
{ k: 10, l: 10 }
end k->l
end j->k
start k->l
{ k: 30, l: 10 }
end k->l
{ i: 30, j: 30, k: 30, l: 30 }
```

It appears that the inner computations are run multiple times, even though they're declared once.

I see that this is required, as otherwise the order of scheduled writes vs outcome wouldn't make sense; for example, since the `i(10)` would immediately set `i=10`, then it makes sense that `j(i())` would work fine, but on the next nested computation, `j` would still be the previous value (0) since it was only scheduled and not yet swapped. Therefore, without running the inner computations again, the result would be `{i:10, j:10, k:0, l:0}`.

This coincides with the test cases for the port I discussed with you:

```
│      ok: i == 0                                  ../test.cc:420
│      ok: j == 0                                  ../test.cc:421
│      ok: k == 0                                  ../test.cc:422
│      ok: l == 0                                  ../test.cc:423
│      ok: outer_calls == 1                        ../test.cc:424
│      ok: middle_calls == 1                       ../test.cc:425
│      ok: inner_calls == 1                        ../test.cc:426
│      ok: i == 10                                 ../test.cc:429
│      ok: j == 10                                 ../test.cc:430
│  not ok: k == 10                                 ../test.cc:431
│  not ok: l == 10                                 ../test.cc:432
```

However, what's the justification for running the inner computations _again_ other than this? The re-run of the inner computation surprised me. Are cleanup functions run as well?

**Comment by Qix-** [comment]
Aha. The scheduling of all dependent signals doesn't happen until _after_ the swap, instead of when the variable was actually referenced.

This makes sense :D

**Comment by adamhaile** [comment]
About your last comment, yes, an important part of S being synchronous is that changes to data signals don't take place until round of updates completes.  Otherwise you'd have a dependency on the order computations ran within the round: did the setter run before or after the referencer?  By "freezing" the world during updates, all computations are guaranteed to see the same state, then at the end of the update round, the world atomically advances to include any changes that the round produced.  (Which then creates another round for any computations that referenced the changed signals, lather rinse repeat until no further changes occur.)

On your earlier point, yeah, that order of executions makes sense to me.  The inner computations aren't re-running in the way we usually think of it, i.e. because a referenced signal changed.  They're being recreated.  Since the computation that created them re-runs, the old inner computation is disposed and a new one created.  The first change re-runs the outermost computation, so all 3 inners are recreated.  Then the mutation triggers the first inner computation to re-run, recreating the 2 inside it.  Etc until the last inner one runs.

If you un-nested them, you'd see that each runs only once, in 4 serial update rounds.
