### ISSUE TITLE
Computed view not updating

### ISSUE THREAD

**Issue by andyjessop** [adamhaile/S#6]
I'm trying to marry `s-js` with `lit-html`, but I can't get the view to update. I've reduced the issue down to the smallest example I could.

This should output `123`, but outputs `12`.
```
import { html, render } from 'lit-html';
import S from 's-js';

const nums = S.data([1, 2]);
const view = S(() => html`<div>${nums()}</div>`);

const r = S.root(() => {
  render(view(), document.getElementById('app'));
});

nums(nums().push(3));
```
The render function is only getting called once. As far as I understand it, that function should also be called as a result of `nums(nums().push(3))`.

Can you enlighten me as to what I'm missing?

Edit: I also tried this with the same output result:
```
const nums = S.data([1, 2]);

const view = S.root(() => html`<div>${nums()}</div>`);

render(view, document.getElementById('app'));

nums(nums().push(3));
```

**Comment by adamhaile** [comment]
The call to `render` isn't 'live' because it's not wrapped in a computation.  So you want something like:
```javascript
S.root(() => S(() =>
  render(view(), document.getElementById('app'))
));
```
`S.root()` controls computations' lifecycles but isn't a computation itself: it only runs once.

I'd be curious to hear how these explorations with lit-html go.  I've done a couple thought experiments about how the two could be combined.

**Comment by andyjessop** [comment]
Great, that works now. Thanks.

I'm just at the start of the project, but will update you as it gets more mature.
